-- migration: 20260415T123417Z_auto_schema_update.sql
-- generated_at_utc: 2026-04-15T12:34:17.888Z
-- notes: no BEGIN/COMMIT here, apply script wraps this file in one transaction.

CREATE TABLE IF NOT EXISTS "openclaw_bindings" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "node_id" varchar, "node_label" varchar, "pairing_status" varchar NOT NULL DEFAULT ('paired'), "enabled" boolean NOT NULL DEFAULT (1), "timeout_seconds" integer NOT NULL DEFAULT (900), "last_seen_at" datetime, "last_dispatched_at" datetime, "last_completed_at" datetime, "last_error" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_208dc96861eee01ac02d9ae2c46" UNIQUE ("user_id"), CONSTRAINT "UQ_6ac29e7d020c15bfa99cbd84f07" UNIQUE ("node_id"), CONSTRAINT "REL_208dc96861eee01ac02d9ae2c4" UNIQUE ("user_id"));
CREATE TABLE IF NOT EXISTS "openclaw_dispatches" ("id" varchar PRIMARY KEY NOT NULL, "binding_id" varchar NOT NULL, "user_id" varchar NOT NULL, "todo_id" varchar NOT NULL, "target_node_id" varchar, "triggered_by_user_id" varchar, "status" varchar NOT NULL DEFAULT ('pending'), "request_content_hash" varchar(64) NOT NULL, "callback_token" varchar(64) NOT NULL, "callback_url" text, "request_payload_json" text, "gateway_response_json" text, "result_text" text, "failure_reason" text, "completed_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS "idx_openclaw_dispatch_user_todo_hash" ON "openclaw_dispatches" ("user_id", "todo_id", "request_content_hash");
CREATE TABLE IF NOT EXISTS "temporary_openclaw_bindings" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "node_id" varchar, "node_label" varchar, "pairing_status" varchar NOT NULL DEFAULT ('paired'), "enabled" boolean NOT NULL DEFAULT (1), "timeout_seconds" integer NOT NULL DEFAULT (900), "last_seen_at" datetime, "last_dispatched_at" datetime, "last_completed_at" datetime, "last_error" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_208dc96861eee01ac02d9ae2c46" UNIQUE ("user_id"), CONSTRAINT "UQ_6ac29e7d020c15bfa99cbd84f07" UNIQUE ("node_id"), CONSTRAINT "REL_208dc96861eee01ac02d9ae2c4" UNIQUE ("user_id"), CONSTRAINT "FK_208dc96861eee01ac02d9ae2c46" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION);
INSERT INTO "temporary_openclaw_bindings"("id", "user_id", "node_id", "node_label", "pairing_status", "enabled", "timeout_seconds", "last_seen_at", "last_dispatched_at", "last_completed_at", "last_error", "created_at", "updated_at") SELECT "id", "user_id", "node_id", "node_label", "pairing_status", "enabled", "timeout_seconds", "last_seen_at", "last_dispatched_at", "last_completed_at", "last_error", "created_at", "updated_at" FROM "openclaw_bindings";
DROP TABLE "openclaw_bindings";
ALTER TABLE "temporary_openclaw_bindings" RENAME TO "openclaw_bindings";
DROP INDEX "idx_openclaw_dispatch_user_todo_hash";
CREATE TABLE IF NOT EXISTS "temporary_openclaw_dispatches" ("id" varchar PRIMARY KEY NOT NULL, "binding_id" varchar NOT NULL, "user_id" varchar NOT NULL, "todo_id" varchar NOT NULL, "target_node_id" varchar, "triggered_by_user_id" varchar, "status" varchar NOT NULL DEFAULT ('pending'), "request_content_hash" varchar(64) NOT NULL, "callback_token" varchar(64) NOT NULL, "callback_url" text, "request_payload_json" text, "gateway_response_json" text, "result_text" text, "failure_reason" text, "completed_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_e9ed8b306f2f61f566520e548bd" FOREIGN KEY ("binding_id") REFERENCES "openclaw_bindings" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_87747905b752485a5f85fad89d6" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_2c63bfe2eccb282988786298ec5" FOREIGN KEY ("todo_id") REFERENCES "todos" ("id") ON DELETE CASCADE ON UPDATE NO ACTION);
INSERT INTO "temporary_openclaw_dispatches"("id", "binding_id", "user_id", "todo_id", "target_node_id", "triggered_by_user_id", "status", "request_content_hash", "callback_token", "callback_url", "request_payload_json", "gateway_response_json", "result_text", "failure_reason", "completed_at", "created_at", "updated_at") SELECT "id", "binding_id", "user_id", "todo_id", "target_node_id", "triggered_by_user_id", "status", "request_content_hash", "callback_token", "callback_url", "request_payload_json", "gateway_response_json", "result_text", "failure_reason", "completed_at", "created_at", "updated_at" FROM "openclaw_dispatches";
DROP TABLE "openclaw_dispatches";
ALTER TABLE "temporary_openclaw_dispatches" RENAME TO "openclaw_dispatches";
CREATE INDEX IF NOT EXISTS "idx_openclaw_dispatch_user_todo_hash" ON "openclaw_dispatches" ("user_id", "todo_id", "request_content_hash");
