-- migration: 20260520T013603Z_auto_schema_update.sql
-- generated_at_utc: 2026-05-20T01:36:03.863Z
-- notes: no BEGIN/COMMIT here, apply script wraps this file in one transaction.

DROP INDEX "idx_todo_ai_suggestions_todo_status";
CREATE TABLE IF NOT EXISTS "temporary_todo_ai_suggestions" ("id" varchar PRIMARY KEY NOT NULL, "session_id" varchar NOT NULL, "todo_id" varchar NOT NULL, "message_id" varchar NOT NULL, "created_by_user_id" varchar NOT NULL, "type" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('pending'), "content" text NOT NULL, "applied_by_user_id" varchar, "applied_progress_entry_id" varchar, "applied_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')));
INSERT INTO "temporary_todo_ai_suggestions"("id", "session_id", "todo_id", "message_id", "created_by_user_id", "type", "status", "content", "applied_by_user_id", "applied_progress_entry_id", "applied_at", "created_at", "updated_at") SELECT "id", "session_id", "todo_id", "message_id", "created_by_user_id", "type", "status", "content", "applied_by_user_id", "applied_progress_entry_id", "applied_at", "created_at", "updated_at" FROM "todo_ai_suggestions";
DROP TABLE "todo_ai_suggestions";
ALTER TABLE "temporary_todo_ai_suggestions" RENAME TO "todo_ai_suggestions";
CREATE INDEX IF NOT EXISTS "idx_todo_ai_suggestions_todo_status" ON "todo_ai_suggestions" ("todo_id", "status");
DROP INDEX "ux_todo_ai_sessions_session_key";
DROP INDEX "ux_todo_ai_sessions_todo_id";
CREATE TABLE IF NOT EXISTS "temporary_todo_ai_sessions" ("id" varchar PRIMARY KEY NOT NULL, "todo_id" varchar NOT NULL, "session_key" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('active'), "last_message_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')));
INSERT INTO "temporary_todo_ai_sessions"("id", "todo_id", "session_key", "status", "last_message_at", "created_at", "updated_at") SELECT "id", "todo_id", "session_key", "status", "last_message_at", "created_at", "updated_at" FROM "todo_ai_sessions";
DROP TABLE "todo_ai_sessions";
ALTER TABLE "temporary_todo_ai_sessions" RENAME TO "todo_ai_sessions";
CREATE UNIQUE INDEX IF NOT EXISTS "ux_todo_ai_sessions_session_key" ON "todo_ai_sessions" ("session_key");
CREATE UNIQUE INDEX IF NOT EXISTS "ux_todo_ai_sessions_todo_id" ON "todo_ai_sessions" ("todo_id");
DROP INDEX "idx_todo_ai_messages_todo_created_at";
DROP INDEX "idx_todo_ai_messages_session_created_at";
CREATE TABLE IF NOT EXISTS "temporary_todo_ai_messages" ("id" varchar PRIMARY KEY NOT NULL, "session_id" varchar NOT NULL, "todo_id" varchar NOT NULL, "user_id" varchar NOT NULL, "role" varchar NOT NULL, "content" text NOT NULL, "openclaw_dispatch_id" varchar, "created_at" datetime NOT NULL DEFAULT (datetime('now')));
INSERT INTO "temporary_todo_ai_messages"("id", "session_id", "todo_id", "user_id", "role", "content", "openclaw_dispatch_id", "created_at") SELECT "id", "session_id", "todo_id", "user_id", "role", "content", "openclaw_dispatch_id", "created_at" FROM "todo_ai_messages";
DROP TABLE "todo_ai_messages";
ALTER TABLE "temporary_todo_ai_messages" RENAME TO "todo_ai_messages";
CREATE INDEX IF NOT EXISTS "idx_todo_ai_messages_todo_created_at" ON "todo_ai_messages" ("todo_id", "created_at");
CREATE INDEX IF NOT EXISTS "idx_todo_ai_messages_session_created_at" ON "todo_ai_messages" ("session_id", "created_at");
DROP INDEX "ux_todo_ai_sessions_session_key";
DROP INDEX "ux_todo_ai_sessions_todo_id";
CREATE TABLE IF NOT EXISTS "temporary_todo_ai_sessions" ("id" varchar PRIMARY KEY NOT NULL, "todo_id" varchar NOT NULL, "session_key" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('active'), "last_message_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')));
INSERT INTO "temporary_todo_ai_sessions"("id", "todo_id", "session_key", "status", "last_message_at", "created_at", "updated_at") SELECT "id", "todo_id", "session_key", "status", "last_message_at", "created_at", "updated_at" FROM "todo_ai_sessions";
DROP TABLE "todo_ai_sessions";
ALTER TABLE "temporary_todo_ai_sessions" RENAME TO "todo_ai_sessions";
CREATE UNIQUE INDEX IF NOT EXISTS "ux_todo_ai_sessions_todo_id" ON "todo_ai_sessions" ("todo_id");
DROP INDEX "ux_todo_ai_sessions_todo_id";
CREATE TABLE IF NOT EXISTS "temporary_todo_ai_sessions" ("id" varchar PRIMARY KEY NOT NULL, "todo_id" varchar NOT NULL, "session_key" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('active'), "last_message_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_2bfecd773560e2162043deb17b1" UNIQUE ("session_key"));
INSERT INTO "temporary_todo_ai_sessions"("id", "todo_id", "session_key", "status", "last_message_at", "created_at", "updated_at") SELECT "id", "todo_id", "session_key", "status", "last_message_at", "created_at", "updated_at" FROM "todo_ai_sessions";
DROP TABLE "todo_ai_sessions";
ALTER TABLE "temporary_todo_ai_sessions" RENAME TO "todo_ai_sessions";
CREATE UNIQUE INDEX IF NOT EXISTS "ux_todo_ai_sessions_todo_id" ON "todo_ai_sessions" ("todo_id");
DROP INDEX "idx_todo_ai_suggestions_todo_status";
CREATE TABLE IF NOT EXISTS "temporary_todo_ai_suggestions" ("id" varchar PRIMARY KEY NOT NULL, "session_id" varchar NOT NULL, "todo_id" varchar NOT NULL, "message_id" varchar NOT NULL, "created_by_user_id" varchar NOT NULL, "type" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('pending'), "content" text NOT NULL, "applied_by_user_id" varchar, "applied_progress_entry_id" varchar, "applied_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_d8a97a63ab9f79cb28c60555c6e" FOREIGN KEY ("session_id") REFERENCES "todo_ai_sessions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_96763451636e6ea0596aca1c2e2" FOREIGN KEY ("todo_id") REFERENCES "todos" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_207471ed5d2259c141c72049a5e" FOREIGN KEY ("message_id") REFERENCES "todo_ai_messages" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_6f99d2afd54dbf178fd9152b384" FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_47415da4636b0b374f791812416" FOREIGN KEY ("applied_by_user_id") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_30fb409e322c0fad8510f40a7ac" FOREIGN KEY ("applied_progress_entry_id") REFERENCES "todo_progress_entries" ("id") ON DELETE SET NULL ON UPDATE NO ACTION);
INSERT INTO "temporary_todo_ai_suggestions"("id", "session_id", "todo_id", "message_id", "created_by_user_id", "type", "status", "content", "applied_by_user_id", "applied_progress_entry_id", "applied_at", "created_at", "updated_at") SELECT "id", "session_id", "todo_id", "message_id", "created_by_user_id", "type", "status", "content", "applied_by_user_id", "applied_progress_entry_id", "applied_at", "created_at", "updated_at" FROM "todo_ai_suggestions";
DROP TABLE "todo_ai_suggestions";
ALTER TABLE "temporary_todo_ai_suggestions" RENAME TO "todo_ai_suggestions";
CREATE INDEX IF NOT EXISTS "idx_todo_ai_suggestions_todo_status" ON "todo_ai_suggestions" ("todo_id", "status");
DROP INDEX "ux_todo_ai_sessions_todo_id";
CREATE TABLE IF NOT EXISTS "temporary_todo_ai_sessions" ("id" varchar PRIMARY KEY NOT NULL, "todo_id" varchar NOT NULL, "session_key" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('active'), "last_message_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_2bfecd773560e2162043deb17b1" UNIQUE ("session_key"), CONSTRAINT "FK_99b3a270dd0e42ca623cc1ee31e" FOREIGN KEY ("todo_id") REFERENCES "todos" ("id") ON DELETE CASCADE ON UPDATE NO ACTION);
INSERT INTO "temporary_todo_ai_sessions"("id", "todo_id", "session_key", "status", "last_message_at", "created_at", "updated_at") SELECT "id", "todo_id", "session_key", "status", "last_message_at", "created_at", "updated_at" FROM "todo_ai_sessions";
DROP TABLE "todo_ai_sessions";
ALTER TABLE "temporary_todo_ai_sessions" RENAME TO "todo_ai_sessions";
CREATE UNIQUE INDEX IF NOT EXISTS "ux_todo_ai_sessions_todo_id" ON "todo_ai_sessions" ("todo_id");
DROP INDEX "idx_todo_ai_messages_todo_created_at";
DROP INDEX "idx_todo_ai_messages_session_created_at";
CREATE TABLE IF NOT EXISTS "temporary_todo_ai_messages" ("id" varchar PRIMARY KEY NOT NULL, "session_id" varchar NOT NULL, "todo_id" varchar NOT NULL, "user_id" varchar NOT NULL, "role" varchar NOT NULL, "content" text NOT NULL, "openclaw_dispatch_id" varchar, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_34fce940a622322492b14b8c981" FOREIGN KEY ("session_id") REFERENCES "todo_ai_sessions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_65776746a4b82c9f016cdeb82ad" FOREIGN KEY ("todo_id") REFERENCES "todos" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_f37a08b6fca9acff40dfd926711" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION);
INSERT INTO "temporary_todo_ai_messages"("id", "session_id", "todo_id", "user_id", "role", "content", "openclaw_dispatch_id", "created_at") SELECT "id", "session_id", "todo_id", "user_id", "role", "content", "openclaw_dispatch_id", "created_at" FROM "todo_ai_messages";
DROP TABLE "todo_ai_messages";
ALTER TABLE "temporary_todo_ai_messages" RENAME TO "todo_ai_messages";
CREATE INDEX IF NOT EXISTS "idx_todo_ai_messages_todo_created_at" ON "todo_ai_messages" ("todo_id", "created_at");
CREATE INDEX IF NOT EXISTS "idx_todo_ai_messages_session_created_at" ON "todo_ai_messages" ("session_id", "created_at");
