-- migration: 20260328T043915Z_schema_baseline.sql
-- generated_at_utc: 2026-03-28T04:39:15.142Z
-- notes: no BEGIN/COMMIT here, apply script wraps this file in one transaction.

CREATE TABLE IF NOT EXISTS "card_participants" ("card_id" varchar NOT NULL, "user_id" varchar NOT NULL, CONSTRAINT "FK_605f28ca5e1c2a68b6482b2ae53" FOREIGN KEY ("card_id") REFERENCES "cards" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_f9547c1e6d6d56801dabc1d386b" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("card_id", "user_id"));
CREATE TABLE IF NOT EXISTS "card_tags" ("card_id" varchar NOT NULL, "tag_id" varchar NOT NULL, CONSTRAINT "FK_8b0e2d4c7a5cd340fc3881d54a4" FOREIGN KEY ("card_id") REFERENCES "cards" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_7cc717b12a493272ebe369ae416" FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("card_id", "tag_id"));
CREATE TABLE IF NOT EXISTS "card_user_layouts" ("id" varchar PRIMARY KEY NOT NULL, "card_id" varchar NOT NULL, "user_id" varchar NOT NULL, "x" integer NOT NULL DEFAULT (0), "y" integer NOT NULL DEFAULT (0), "w" integer NOT NULL DEFAULT (4), "h" integer NOT NULL DEFAULT (4), "layouts_json" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_f99c9e5dccd4d3daaf7d2671102" UNIQUE ("card_id", "user_id"), CONSTRAINT "FK_9ff24ac7936c6bc078629b450fb" FOREIGN KEY ("card_id") REFERENCES "cards" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_6c7e87e86419bb51279c084bca5" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS "cards" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "name" varchar NOT NULL, "card_type" varchar NOT NULL DEFAULT ('personal'), "sort_by" varchar NOT NULL DEFAULT ('due_at'), "sort_order" varchar NOT NULL DEFAULT ('asc'), "x" integer NOT NULL DEFAULT (0), "y" integer NOT NULL DEFAULT (0), "w" integer NOT NULL DEFAULT (4), "h" integer NOT NULL DEFAULT (4), "plugin_type" varchar NOT NULL DEFAULT ('local_todo'), "plugin_config_json" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "userId" varchar, CONSTRAINT "FK_7b7230897ecdeb7d6b0576d907b" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS "email_codes" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "email" varchar NOT NULL, "code" varchar NOT NULL, "purpose" varchar NOT NULL DEFAULT ('verify_email'), "expires_at" datetime NOT NULL, "used_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "userId" varchar, CONSTRAINT "FK_cd16d9d1900e92bc32425ba7ac8" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS "miniapp_bindings" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "mini_open_id" varchar NOT NULL, "mini_union_id" varchar, "mini_nickname" varchar, "mini_avatar_url" varchar, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "REL_2e80f0c2f7fc8786c620c783e7" UNIQUE ("user_id"), CONSTRAINT "FK_2e80f0c2f7fc8786c620c783e72" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS "tags" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "name" varchar(20) NOT NULL, "color" varchar(20), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "userId" varchar, CONSTRAINT "UQ_1d8718578ce96a09d1aa2237a14" UNIQUE ("user_id", "name"), CONSTRAINT "FK_92e67dc508c705dd66c94615576" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS "tapd_configs" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "apiUrl" varchar NOT NULL, "workspaceId" varchar NOT NULL, "isDefault" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS "todo_assignees" ("todo_id" varchar NOT NULL, "user_id" varchar NOT NULL, CONSTRAINT "FK_f735bcc20b23ea6888087e8f36c" FOREIGN KEY ("todo_id") REFERENCES "todos" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_c6ff6d83f4ed316588f31940fa5" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("todo_id", "user_id"));
CREATE TABLE IF NOT EXISTS "todo_calendar_sync_records" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "todo_id" varchar NOT NULL, "device_id" varchar NOT NULL, "synced_deadline_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_abe11a209add1cfd6547b6e192a" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_a8517d03b0610719ae09670b10c" FOREIGN KEY ("todo_id") REFERENCES "todos" ("id") ON DELETE CASCADE ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS "todo_progress_entries" ("id" varchar PRIMARY KEY NOT NULL, "todo_id" varchar NOT NULL, "user_id" varchar NOT NULL, "content" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_fc210a923ebc44d385c88240b5f" FOREIGN KEY ("todo_id") REFERENCES "todos" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_df9126d69108ce82c04daa41505" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS "todo_tags" ("todo_id" varchar NOT NULL, "tag_id" varchar NOT NULL, CONSTRAINT "FK_995af982f546b93672fe0ae6525" FOREIGN KEY ("todo_id") REFERENCES "todos" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_425e9a5498a6e434e3c6335b289" FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("todo_id", "tag_id"));
CREATE TABLE IF NOT EXISTS "todos" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "card_id" varchar, "content" varchar NOT NULL, "due_at" datetime, "execute_at" datetime, "status" varchar NOT NULL DEFAULT ('todo'), "completed_at" datetime, "deleted_at" datetime, "progress_count" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "userId" varchar, "cardId" varchar, CONSTRAINT "FK_4583be7753873b4ead956f040e3" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_6549964793bfb2dc9780c2f1c77" FOREIGN KEY ("cardId") REFERENCES "cards" ("id") ON DELETE CASCADE ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS "users" ("id" varchar PRIMARY KEY NOT NULL, "email" varchar NOT NULL, "password_hash" varchar NOT NULL, "nickname" varchar, "avatar_url" varchar, "target" varchar, "email_verified" boolean NOT NULL DEFAULT (0), "status" varchar NOT NULL DEFAULT ('active'), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"));
CREATE INDEX IF NOT EXISTS "IDX_425e9a5498a6e434e3c6335b28" ON "todo_tags" ("tag_id");
CREATE INDEX IF NOT EXISTS "IDX_605f28ca5e1c2a68b6482b2ae5" ON "card_participants" ("card_id");
CREATE INDEX IF NOT EXISTS "IDX_7cc717b12a493272ebe369ae41" ON "card_tags" ("tag_id");
CREATE INDEX IF NOT EXISTS "IDX_8b0e2d4c7a5cd340fc3881d54a" ON "card_tags" ("card_id");
CREATE INDEX IF NOT EXISTS "IDX_995af982f546b93672fe0ae652" ON "todo_tags" ("todo_id");
CREATE INDEX IF NOT EXISTS "IDX_c6ff6d83f4ed316588f31940fa" ON "todo_assignees" ("user_id");
CREATE INDEX IF NOT EXISTS "IDX_f735bcc20b23ea6888087e8f36" ON "todo_assignees" ("todo_id");
CREATE INDEX IF NOT EXISTS "IDX_f9547c1e6d6d56801dabc1d386" ON "card_participants" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_todo_progress_todo_created_at" ON "todo_progress_entries" ("todo_id", "created_at");
CREATE INDEX IF NOT EXISTS "idx_todo_progress_user_created_at" ON "todo_progress_entries" ("user_id", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "ux_miniapp_bindings_open_id" ON "miniapp_bindings" ("mini_open_id");
CREATE UNIQUE INDEX IF NOT EXISTS "ux_miniapp_bindings_user" ON "miniapp_bindings" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "ux_todo_calendar_sync_records_key" ON "todo_calendar_sync_records" ("user_id", "todo_id", "device_id");
